name: Build Android APK

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1  # Update to v2
        id: buildozer
        with:
          workdir: app
          buildozer_version: stable
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: app/bin/*.apk